name: gobot-blinkk-arun1930
version: master
summary:  Blink snap for the Raspberry Pi with Gobot
description: |
  This is a simple example to blink an LED in the Raspberry Pi
  using the Gobot framework.

confinement: strict

apps:
   gobot-blinkk-arun1930: 
    command: gobot-blink
    plugs:
      - gpio

parts:
   gobot-blink:
    source: .
    plugin: go
    go-importpath: github.com/Arun1930/gobot-blink-snap
